application: mnk
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: misc/home.html
  upload: misc/home\.html

- url: /favicon\.ico
  mime_type: image/gif
  static_files: misc/favicon.gif
  upload: misc/favicon\.gif

- url: /robots.txt
  static_files: misc/robots.txt
  upload: misc/robots\.txt

- url: /(.*\.(css|js))
  static_files: \2/\1
  upload: (css|js)/(.*\.\1)

- url: /(.*\.(gif|jpg|png))
  static_files: img/\1
  upload: img/.+\.(gif|jpg|png)

- url: /.*
  script: main.py
